import { type FastifyInstance } from "fastify";
import { registerAttendanceRoutes } from "./attendance";
import { registerAuthRoutes } from "./auth";
import { registerCaseRoutes } from "./cases";
import { registerClientRoutes } from "./clients";
import { registerClockPointRoutes } from "./clockPoints";
import { registerCompanyRoutes } from "./companies";
import { registerCompensationRoutes } from "./compensation";
import { registerDiplomaRoutes } from "./diploma";
import { registerDocumentCategoryRoutes } from "./documentCategories";
import { registerDocumentRoutes } from "./documents";
import { registerEmployeeRoutes } from "./employees";
import { registerEnglishRoutes } from "./english";
import { registerFaceChallengeRoutes } from "./faceChallenges";
import { registerHealthRoutes } from "./health";
import { registerKpiRoutes } from "./kpi";
import { registerPayslipRoutes } from "./payslip";
import { registerPerformanceRoutes } from "./performance";
import { registerPositionRoutes } from "./positions";
import { registerSiteVisitRoutes } from "./siteVisits";
import { registerStatutoryRoutes } from "./statutory";
import { registerStudentRoutes } from "./students";
import { registerTaskRoutes } from "./tasks";
import { registerTrackingRoutes } from "./tracking";
import { registerWorkShiftRoutes } from "./workShifts";
import { registerWorkflowTemplateRoutes } from "./workflowTemplates";
import { registerWsqRoutes } from "./wsq";

export async function registerRoutes(app: FastifyInstance): Promise<void> {
  await app.register(registerHealthRoutes);
  await app.register(registerAuthRoutes);
  await app.register(registerEmployeeRoutes);
  await app.register(registerCompanyRoutes);
  await app.register(registerPositionRoutes);
  await app.register(registerWorkShiftRoutes);
  await app.register(registerCompensationRoutes);
  await app.register(registerTaskRoutes);
  await app.register(registerAttendanceRoutes);
  await app.register(registerClockPointRoutes);
  await app.register(registerKpiRoutes);
  await app.register(registerPerformanceRoutes);
  await app.register(registerStatutoryRoutes);
  await app.register(registerPayslipRoutes);
  await app.register(registerSiteVisitRoutes);
  await app.register(registerTrackingRoutes);
  await app.register(registerFaceChallengeRoutes);
  await app.register(registerClientRoutes);
  await app.register(registerWorkflowTemplateRoutes);
  await app.register(registerCaseRoutes);
  await app.register(registerDocumentCategoryRoutes);
  await app.register(registerDocumentRoutes);
  await app.register(registerStudentRoutes);
  await app.register(registerDiplomaRoutes);
  await app.register(registerWsqRoutes);
  await app.register(registerEnglishRoutes);
}
