import { type FastifyInstance } from "fastify";
import { registerAttendanceRoutes } from "./attendance";
import { registerAuthRoutes } from "./auth";
import { registerBillingRoutes } from "./billing";
import { registerBusinessRoutes } from "./businesses";
import { registerCaseRoutes } from "./cases";
import { registerClientRoutes } from "./clients";
import { registerClockPointRoutes } from "./clockPoints";
import { registerCompanyRoutes } from "./companies";
import { registerCompanyExpenseRoutes } from "./companyExpenses";
import { registerCompensationRoutes } from "./compensation";
import { registerDealPartyRoutes } from "./dealParties";
import { registerContractRoutes } from "./contracts";
import { registerDiplomaCourseRoutes } from "./diplomaCourses";
import { registerDiplomaRoutes } from "./diploma";
import { registerDocumentCategoryRoutes } from "./documentCategories";
import { registerDocumentRoutes } from "./documents";
import { registerEmployeeRoutes } from "./employees";
import { registerEnglishRoutes } from "./english";
import { registerFaceChallengeRoutes } from "./faceChallenges";
import { registerGuarantorRoutes } from "./guarantors";
import { registerGeocodeRoutes } from "./geocode";
import { registerHealthRoutes } from "./health";
import { registerIndustryRoutes } from "./industries";
import { registerKpiRoutes } from "./kpi";
import { registerPayslipRoutes } from "./payslip";
import { registerPerformanceRoutes } from "./performance";
import { registerPositionRoutes } from "./positions";
import { registerSchemeVersionRoutes } from "./schemeVersions";
import { registerSiteVisitRoutes } from "./siteVisits";
import { registerStatutoryRoutes } from "./statutory";
import { registerStudentRoutes } from "./students";
import { registerTaskRoutes } from "./tasks";
import { registerTrackingRoutes } from "./tracking";
import { registerWorkShiftRoutes } from "./workShifts";
import { registerWorkflowTemplateRoutes } from "./workflowTemplates";
import { registerWsqRoutes } from "./wsq";

export async function registerRoutes(app: FastifyInstance): Promise<void> {
  await app.register(registerHealthRoutes);
  await app.register(registerAuthRoutes);
  await app.register(registerBillingRoutes);
  await app.register(registerBusinessRoutes);
  await app.register(registerSchemeVersionRoutes);
  await app.register(registerDealPartyRoutes);
  await app.register(registerEmployeeRoutes);
  await app.register(registerCompanyRoutes);
  await app.register(registerIndustryRoutes);
  await app.register(registerPositionRoutes);
  await app.register(registerWorkShiftRoutes);
  await app.register(registerCompensationRoutes);
  await app.register(registerTaskRoutes);
  await app.register(registerAttendanceRoutes);
  await app.register(registerClockPointRoutes);
  await app.register(registerGeocodeRoutes);
  await app.register(registerKpiRoutes);
  await app.register(registerPerformanceRoutes);
  await app.register(registerStatutoryRoutes);
  await app.register(registerPayslipRoutes);
  await app.register(registerSiteVisitRoutes);
  await app.register(registerTrackingRoutes);
  await app.register(registerFaceChallengeRoutes);
  await app.register(registerClientRoutes);
  await app.register(registerWorkflowTemplateRoutes);
  await app.register(registerCaseRoutes);
  await app.register(registerGuarantorRoutes);
  await app.register(registerDocumentCategoryRoutes);
  await app.register(registerDocumentRoutes);
  await app.register(registerCompanyExpenseRoutes);
  await app.register(registerContractRoutes);
  await app.register(registerStudentRoutes);
  await app.register(registerDiplomaCourseRoutes);
  await app.register(registerDiplomaRoutes);
  await app.register(registerWsqRoutes);
  await app.register(registerEnglishRoutes);
}
